# Generated by Django 4.1.6 on 2023-02-10 22:24

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='slug',
            field=models.SlugField(default='asdasdasd'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='status',
            field=models.BooleanField(default=0, verbose_name='Aktif / Pasif'),
        ),
    ]
