# Generated by Django 4.1.6 on 2023-02-10 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_blogmodel_content_blogmodel_slug_blogmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='slug',
            field=models.SlugField(editable=False),
        ),
    ]
